account/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [path("", views.index, name="index")]

register/urls.py
from django.urls import path
from . import views

app_name = "register"

urlpatterns = [
    path("", views.property_list, name="property_list"),
    path("form_upload/", views.form_upload, name="form_upload"),
    path("import_data/", views.import_data, name="import_data")
]

sigweb/urls.py
from django.urls import path
from . import views

app_name = "sigweb"

urlpatterns = [
    path("", views.map, name="map"),
    path("click/<path:lng>/<path:lat>/", views.click_map, name="click_map"),
]

urbangeosig/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls")),
    path("map/", include("sigweb.urls")),
    path("account/", include("account.urls")),
    path("register/", include("register.urls")),
    path("admin/", admin.site.urls),
]

account/models.py
from django.db import models

# Create your models here.

core/models.py
from django.contrib.gis.db import models


class BaseModel(models.Model):
    ativo = models.BooleanField("Ativo", default=True)
    criado = models.DateTimeField("Criado", auto_now=True)
    modificado = models.DateTimeField("Modificado", auto_now=True)

    class Meta:
        abstract = True

register/models.py
from django.contrib.gis.db import models
from core.models import BaseModel


class Setor(BaseModel):
    num_setor = models.CharField("Número do setor", unique=True, max_length=20)
    geom = models.MultiPolygonField("Geometria", srid=4326)

    def __str__(self):
        return self.num_setor

    class Meta:
        verbose_name = "Setor"
        verbose_name_plural = "Setores"


class Quadra(BaseModel):
    num_quadra = models.CharField("Número da quadra", max_length=20)
    setor = models.ForeignKey("Setor", verbose_name="Setor", on_delete=models.PROTECT)
    geom = models.MultiPolygonField("Geometria", srid=4326)

    def __str__(self):
        return self.num_quadra

    class Meta:
        verbose_name = "Quadra"
        verbose_name_plural = "Quadras"


class Lote(BaseModel):
    SITUACAO_CHOICES = (
        ("a-ser-atendido", "A ser atendido"),
        ("lote-cadastrado", "Lote cadastrado"),
        ("lote-titulado", "Lote titulado"),
    )
    num_lote = models.CharField("Número do lote", max_length=20)
    situacao = models.CharField("Situação", max_length=20, choices=SITUACAO_CHOICES)
    quadra = models.ForeignKey(
        "Quadra", verbose_name="Quadra", on_delete=models.PROTECT
    )
    geom = models.MultiPolygonField("Geometria", srid=4326)

    def __str__(self):
        return self.num_lote

    def popup(self):
        popup = "<ul>"
        popup += f"<li><span>Número do lote:</span> {self.num_lote}</li>"
        popup += f"<li><span>Situação:</span> {self.get_situacao_display()}</li>"
        popup += f"<li><span>Número da quadra:</span> {self.quadra}</li>"
        popup += f"<li><span>Número do setor:</span> {self.quadra.setor}</li>"
        popup += "</ul>"

        return popup

    class Meta:
        verbose_name = "Lote"
        verbose_name_plural = "Lotes"

sigweb/models.py
from django.db import models

# Create your models here.

account/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages


class Login(LoginView, SuccessMessageMixin):
    template_name = "account/auth.html"
    redirect_authenticated_user = True
    success_message = "UrbanGeoSIG - Sessão iniciada com sucesso!"


class Logout(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)
        messages.add_message(
            request,
            messages.INFO,
            "UrbanGeoSIG - Sua sessão foi encerrada com sucesso!",
        )
        return response


login = Login.as_view()
logout = Logout.as_view()

core/views.py
from django.shortcuts import render


def index(request):
    return render(request, "core/index.html")

register/views.py
from django.shortcuts import render, redirect
from register.tasks import import_data_async


def property_list(request):
    return render(request, "register/property_list.html")


def form_upload(request):
    if request.method == "POST":
        shapefile = request.FILES.get("shapefile")

        if shapefile:
            with open("temp.gpkg", "wb") as f:
                for chunk in shapefile.chunks():
                    f.write(chunk)
            return redirect("register:import_data")

    return render(request, "register/form_upload.html")


def import_data(request):
    geopackage = "temp.gpkg"
    import_data_async.delay(geopackage)

    return redirect("sigweb:map")

sigweb/views.py
from django.shortcuts import render
from sigweb.tasks import query_lote


def map(request):
    return render(request, "sigweb/map.html")


def click_map(request, lng, lat):
    result = query_lote.delay(lng, lat)
    task_result = result.get()
    lote_popup = task_result["lote_popup"] if task_result else None
    lng = task_result["lng"] if task_result else None
    lat = task_result["lat"] if task_result else None

    context = {
        "lote_popup": lote_popup,
        "lng": lng,
        "lat": lat,
    }

    return render(request, "sigweb/click_map.html", context)

core/templates/base.html
{% load static bootstrap5 %}

<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>UrbanGeoSIG</title>
    <link
      rel="stylesheet"
      href="{% static 'vendor/bootstrap-5.3.0-dist/css/bootstrap.min.css' %}"
    />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="shortcut icon" href="{% static 'img/map_icon.svg' %}" type="image/x-icon">
    <script src="{% static 'vendor/fontawesome/f200917737.js' %}"></script>
    {% block extra_css %}{% endblock extra_css %}
  </head>
  <body>
    {% include 'includes/navbar.html' %}

    <div id="msg">
      {% bootstrap_messages %}
    </div>

    {% block content %}{% endblock content %}

    <script src="{% static 'vendor/jquery/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap-5.3.0-dist/js/bootstrap.bundle.min.js' %}"></script>
    <script>
      $("#msg").show().delay(5000).fadeOut();
    </script>

    {% block extra_js %}{% endblock extra_js %}
  </body>
</html>

core/templates/core/index.html
{% extends 'base.html' %} {% block content %}
<div class="p-5 mb-4 bg-light rounded-3">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold">
      <i class="fa-solid fa-city"></i>
      UrbanGeoSIG
    </h1>
    <p class="col-md-8 fs-4">
      Sistema de Georreferenciamento voltado para a gestão de prefeituras
    </p>
    <a
      href="{% url 'sigweb:map' %}"
      class="btn btn-success btn-lg"
      role="button"
    >
      <i class="fa-solid fa-right-to-bracket"></i> Acessar
    </a>
  </div>
</div>
{% endblock content %}

core/templates/includes/navbar.html
{% with request.resolver_match.url_name as url_name %}
<nav
  class="navbar navbar-expand-md navbar-dark bg-dark"
  aria-label="Fourth navbar example"
>
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'core:index' %}">
      <i class="fa-solid fa-city"></i>
      UrbanGeoSIG
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarsExample04"
      aria-controls="navbarsExample04"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExample04">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a
            class="nav-link {% if url_name == 'index' %}active{% endif %}"
            aria-current="page"
            href="{% url 'core:index' %}"
          >
            <i class="fa-solid fa-home"></i>
            Início
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link {% if url_name == 'map' %}active{% endif %}"
            href="{% url 'sigweb:map' %}"
          >
            <i class="fa-solid fa-map"></i>
            Mapa
          </a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a
            class="nav-link {% if url_name == 'property_list' %}active{% endif %}"
            href="{% url 'register:property_list' %}"
          >
            <i class="fa-solid fa-list"></i>
            Relação dos imóveis
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        {% if not request.user.is_authenticated %}
        <li class="nav-item">
          <a
            class="nav-link {% if url_name == 'login' %}active{% endif %}"
            href="{% url 'account:login' %}"
          >
            <i class="fa-solid fa-right-to-bracket"></i>
            Iniciar sessão
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a
            class="nav-link {% if url_name == 'logout' %}active{% endif %}"
            href="{% url 'account:logout' %}"
          >
            <i class="fa-solid fa-right-from-bracket"></i>
            Encerrar sessão
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
{% endwith %}

register/templates/register/form_upload.html
{% extends 'base.html' %} {% block content %}
<div
  class="container d-flex justify-content-center align-items-center"
  style="min-height: 100vh"
>
  <div class="">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group mb-2">
        <label for="shapefile" class="custom-file-upload">
          Escolha um arquivo
          <input
            type="file"
            name="shapefile"
            class="custom-file-input"
            id="shapefile"
            required
          />
        </label>
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-primary w-100">Importar</button>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

register/templates/register/property_list.html
{% extends 'base.html' %} {% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 mt-4">
      <div class="card">
        <div class="card-header">
          <i class="fa-solid fa-list"></i>
          Relação dos imóveis
        </div>
        <div class="card-body">
          <div class="row">
            <form class="m-2">
              <div class="row">
                <div class="col-md-3">
                  <label for="setor" class="form-label">Setor</label>
                  <input
                    type="text"
                    class="form-control"
                    id="setor"
                    aria-describedby="setorHelp"
                  />
                  <div id="setorHelp" class="form-text">
                    Digite o número do setor
                  </div>
                </div>
                <div class="col-md-3">
                  <label for="quadra" class="form-label">Quadra</label>
                  <input
                    type="text"
                    class="form-control"
                    id="quadra"
                    aria-describedby="quadraHelp"
                  />
                  <div id="quadraHelp" class="form-text">
                    Digite o número da quadra
                  </div>
                </div>
                <div class="col-md-3">
                  <label for="lote" class="form-label">Lote</label>
                  <input
                    type="text"
                    class="form-control"
                    id="lote"
                    aria-describedby="loteHelp"
                  />
                  <div id="loteHelp" class="form-text">
                    Digite o número do lote
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="pt-4">
                    <button type="button" class="btn btn-primary btn-search">
                      <i class="fa-solid fa-magnifying-glass-location"></i>
                      Buscar
                    </button>
                    <button type="button" class="btn btn-warning btn-search">
                      <i class="fa-solid fa-rotate-left"></i>
                      Limpar
                    </button>
                  </div>
                </div>
              </div>
            </form>
            <div class="col-md-12 mt-4 p-4">
              <a
                href="{% url 'register:form_upload' %}"
                class="btn btn-primary mb-4"
                role="button"
              >
                <i class="fa-solid fa-circle-plus"></i>
                Adicionar imóvel
              </a>
              <table class="table table-striped table-hover">
                <thead class="table-light">
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Código</th>
                    <th scope="col">Setor</th>
                    <th scope="col">Quadra</th>
                    <th scope="col">Lote</th>
                    <th scope="col">Ações</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">1</th>
                    <td>123456</td>
                    <td>01</td>
                    <td>02</td>
                    <td>245</td>
                    <td>
                      <a
                        href="property_detail.html"
                        class="btn btn-primary"
                        role="button"
                      >
                        <i class="fa fa-info-circle"></i>
                      </a>
                      <a href="#" class="btn btn-warning" role="button">
                        <i class="fa-solid fa-pen-to-square"></i>
                      </a>
                      <button
                        type="button"
                        class="btn btn-danger"
                        data-bs-toggle="modal"
                        data-bs-target="#exampleModal"
                      >
                        <i class="fa-solid fa-trash"></i>
                      </button>
                    </td>
                  </tr>
                  <tr>
                    <th scope="row">2</th>
                    <td>543260</td>
                    <td>05</td>
                    <td>12</td>
                    <td>102-A</td>
                    <td>
                      <a href="#" class="btn btn-primary" role="button">
                        <i class="fa fa-info-circle"></i>
                      </a>
                      <a href="#" class="btn btn-warning" role="button">
                        <i class="fa-solid fa-pen-to-square"></i>
                      </a>
                      <a href="#" class="btn btn-danger" role="button">
                        <i class="fa-solid fa-trash"></i>
                      </a>
                    </td>
                  </tr>
                </tbody>
              </table>
              <div
                class="modal fade"
                id="exampleModal"
                tabindex="-1"
                aria-labelledby="exampleModalLabel"
                aria-hidden="true"
              >
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">
                        Remover imóvel 1
                      </h5>
                      <button
                        type="button"
                        class="btn-close"
                        data-bs-dismiss="modal"
                        aria-label="Close"
                      ></button>
                    </div>
                    <div class="modal-body">
                      Tem certeza que deseja deletar este registro?
                    </div>
                    <div class="modal-footer">
                      <button
                        type="button"
                        class="btn btn-secondary"
                        data-bs-dismiss="modal"
                      >
                        <i class="fa-solid fa-ban"></i>
                        Voltar
                      </button>
                      <button type="button" class="btn btn-danger">
                        <i class="fa-solid fa-trash"></i>
                        Remover
                      </button>
                    </div>
                  </div>
                </div>
              </div>
              <nav aria-label="Page navigation example">
                <ul class="pagination">
                  <li class="page-item">
                    <a class="page-link" href="#"> << </a>
                  </li>
                  <li class="page-item"><a class="page-link" href="#">1</a></li>
                  <li class="page-item"><a class="page-link" href="#">2</a></li>
                  <li class="page-item"><a class="page-link" href="#">3</a></li>
                  <li class="page-item">
                    <a class="page-link" href="#"> >> </a>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

sigweb/templates/sigweb/click_map.html
{% if lote_popup %} {{ lote_popup|safe }} {% else %} ****** {% endif %}

sigweb/templates/sigweb/map.html
{% extends 'base.html' %} {% load static core_tags %} {% block extra_css %}
<link rel="stylesheet" href="{% static 'vendor/leaflet/leaflet.css' %}" />
<link
  rel="stylesheet"
  href="{% static 'vendor/leaflet/plugins/zoom_to_home/leaflet.zoomhome.css' %}"
/>
{% endblock extra_css %} {% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 mt-4">
      <div class="card">
        <div class="card-header">
          <button
            class="btn btn-light"
            type="button"
            data-bs-toggle="offcanvas"
            data-bs-target="#offcanvasBottom"
            aria-controls="offcanvasBottom"
          >
            <i class="fa-solid fa-magnifying-glass-location"></i>
            Pesquisar
          </button>
        </div>
        <div class="card-body map-card-body">
          <div id="map"></div>
          <input
            type="hidden"
            id="geoserver"
            value="{% settings_value 'GEOSERVER' %}"
          />
          <input
            type="hidden"
            id="click"
            value="{% url 'sigweb:click_map' 0 0 %}"
          />
        </div>
      </div>
    </div>
  </div>
</div>
<div
  class="offcanvas offcanvas-bottom"
  tabindex="-1"
  id="offcanvasBottom"
  aria-labelledby="offcanvasBottomLabel"
>
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasBottomLabel">
      <i class="fa-solid fa-magnifying-glass-location"></i>
      Pesquisar
    </h5>
    <button
      type="button"
      class="btn-close text-reset"
      data-bs-dismiss="offcanvas"
      aria-label="Close"
    ></button>
  </div>
  <div class="offcanvas-body small">
    <form>
      <div class="row">
        <div class="col-md-3">
          <label for="setor" class="form-label">Setor</label>
          <input
            type="text"
            class="form-control"
            id="setor"
            aria-describedby="setorHelp"
          />
          <div id="setorHelp" class="form-text">Digite o número do setor</div>
        </div>
        <div class="col-md-3">
          <label for="quadra" class="form-label">Quadra</label>
          <input
            type="text"
            class="form-control"
            id="quadra"
            aria-describedby="quadraHelp"
          />
          <div id="quadraHelp" class="form-text">Digite o número da quadra</div>
        </div>
        <div class="col-md-3">
          <label for="lote" class="form-label">Lote</label>
          <input
            type="text"
            class="form-control"
            id="lote"
            aria-describedby="loteHelp"
          />
          <div id="loteHelp" class="form-text">Digite o número do lote</div>
        </div>
        <div class="col-md-3">
          <div class="pt-4">
            <button type="button" class="btn btn-primary btn-search">
              <i class="fa-solid fa-magnifying-glass-location"></i>
              Limpar
            </button>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock content %} {% block extra_js %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'vendor/leaflet/leaflet.js' %}"></script>
<script src="{% static 'vendor/leaflet/plugins/zoom_to_home/leaflet.zoomhome.js' %}"></script>
<script src="{% static 'js/mainmap.js' %}"></script>
{% endblock extra_js %}